### ISSUE TITLE
FCE Compatibility

### ISSUE THREAD

**Issue by adam1x** [ScottyLabs/course-api#28]
`Authenticating...
Downloading data for div 683...
Parsing...
Something went wrong. Running without FCEs for now...`

I guess they updated FCE HTML template?

**Comment by justingallagher** [comment]
Yes, they made some changes to the FCEs site that broke our authentication scheme. I've been trying to figure it out over the past few weeks but haven't had much luck.

I'm been thinking about providing a workaround so you could go to the [FCEs website](http://cmu.smartevals.com), download the data for the semesters/colleges you want, then run the script on that locally. Would that work for your application? Of course, you'd have to repeat this as new FCEs are released.

(Continuation of #27)

**Comment by adam1x** [comment]
oh nevermind. I'm just using all the data from catalog to easily check pre-reqs and co-reqs.
