### ISSUE TITLE
Combine lectures and sections

### ISSUE THREAD

**Issue by justinchuby** [ScottyLabs/course-api#42]
Since lectures and sections have similar properties, should we combine lectures and sections into one big list?
This would make searching easier.

**Comment by nitsanshai** [comment]
I'd be inclined to say no, it's actually much easier to distinguish and use
them when they're separated (as a user).

**Comment by justingallagher** [comment]
I think we should keep them separate - the distinction between the two is necessary, and usually you can only be part of one lecture and one recitation.
