### ISSUE TITLE
Speed up parsing with multithreading

### ISSUE THREAD

**Issue by justinchuby** [ScottyLabs/course-api#45]
We may use multithreading to speed up the parsing process.

**Comment by yiblet** [comment]
How would that be implemented?

**Comment by justinchuby** [comment]
I think we can use threading and Queue. Use multiple threads to get data and parse them all together.

**Comment by yiblet** [comment]
You know what, I have some time to kill today, I think I will try to implement this today. I'll make a feature branch and merge to master once it's ready

**Comment by justinchuby** [comment]
That'll be great!

**Comment by yiblet** [comment]
Actually, I changed my mind, I'll do this via forking and pull requesting. I don't want to circumvent to usual process to do this.

**Comment by justingallagher** [comment]
Thanks @yiblet! The relevant bit of code is in [aggregate.py](https://github.com/ScottyLabs/course-api/blob/master/cmu_course_api/aggregate.py#L40) - that loop can be made parallel pretty easily.
